
project_id = "cxvdcdatxewrvwbcnksg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
port = 54325

[storage]
enabled = true
port = 54326

[functions]
enabled = true
port = 54327

[functions.analyze-property]
verify_jwt = false

[functions.generate-3d-model]
verify_jwt = false

[functions.get-google-maps-key]
verify_jwt = false

[functions.flexoffers-webhook]
verify_jwt = false

[functions.process-submission]
verify_jwt = false

[functions.solar-api]
verify_jwt = false
