
# Supabase project configuration
project_id = "cxvdcdatxewrvwbcnksg"

[api]
# Port to run the API on. Defaults to 54321.
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
# Port to run the DB on. Defaults to 54322.
port = 54322

[studio]
# Port to run Studio on. Defaults to 54323.
port = 54323

[functions]
[functions.flexoffers_webhook]
verify_jwt = false

[inbucket]
# Port to run the SMTP server on. Defaults to 54324.
port = 54324
# Port to run the POP3 server on. Defaults to 54325.
pop3_port = 54325
# Port to run the inbucket UI on. Defaults to 54324.
web_port = 54326
# Web UI domain. Set to localhost by default.
web_url = "http://localhost"

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"
