// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivhlopzrzrdfrjezolge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2aGxvcHpyenJkZnJqZXpvbGdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMjg4ODUsImV4cCI6MjA2MTgwNDg4NX0.I9-F6HtsXWL2uvwBbJNhG9E0tmgZ2Qq-U4f-fZGk4NM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);