// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huobfidabwbxdrtnktng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1b2JmaWRhYndieGRydG5rdG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjYwNTksImV4cCI6MjA2OTkwMjA1OX0.UsgkQi3eATCR9DZdgbbNzVey0MtIwKmJk13Kesv-J4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});